import AuthProvider from "@/components/providers/SessionProvider";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { Gochi_Hand } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const openSans = Gochi_Hand({ subsets: ["latin"], weight: ["400"] });

export default async function RootLayout({ children }: { children: React.ReactNode }) {
    const session = await getServerSession();
    return (
        <html lang="en">
            <body className={cn(openSans.className)}>
                <ThemeProvider attribute="class" defaultTheme="dark" disableTransitionOnChange>
                    <AuthProvider session={session}>{children}</AuthProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}

